baseURL = "https://blog.ctmartin.me/"
copyright = "2019 Christian Martin"
disableHugoGeneratorInject = true
languageCode = "en-us"
paginatePath = ""
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
theme = ["ctmartin"]

[Authors.ctmartin]
  given_name = "Christian"
  family_name = "Martin"
  display_name = "Christian Martin"
[Authors.ctmartin.social]
    website = "https://ctmartin.me/"
    github = "ct-martin"
    twitter = "_ctmartin"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]

[params]
  author = "Christian Martin"
  description = "Christian Martin's Blog"
  sourceurl = "https://github.com/ct-martin/blog.ctmartin.me/"
  title = "Christian Martin's Blog"

[permalinks]
  blog = "/:year/:month/:filename/"

[[menu.main]]
    name = "Posts"
    idenfifier = "posts"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Portfolio"
    idenfifier = "portfolio"
    url = "https://ctmartin.me/"
    weight = 20
[[menu.main]]
    name = "About"
    idenfifier = "about"
    url = "https://ctmartin.me/about"
    weight = 30